/*
Notes to play the Clocks
*/

Note clocks[] = {
  {NOTE_D4,  EIGHTH},
  {NOTE_A4,  EIGHTH},
  {NOTE_F3,  EIGHTH},
  {NOTE_D4,  EIGHTH},
  {NOTE_A4,  EIGHTH},
  {NOTE_F3,  EIGHTH},
  {NOTE_D4,  EIGHTH},
  {NOTE_A4,  EIGHTH},
  {NOTE_C4,  EIGHTH},
  {NOTE_A4,  EIGHTH},
  {NOTE_E3,  EIGHTH},
  {NOTE_C4,  EIGHTH},
  {NOTE_A4,  EIGHTH},
  {NOTE_E3,  EIGHTH},
  {NOTE_C4,  EIGHTH},
  {NOTE_A4,  EIGHTH},
  {NOTE_C4,  EIGHTH},
  {NOTE_A4,  EIGHTH},
  {NOTE_E3,  EIGHTH},
  {NOTE_C4,  EIGHTH},
  {NOTE_A4,  EIGHTH},
  {NOTE_E3,  EIGHTH},
  {NOTE_C4,  EIGHTH},
  {END_NOTES,  END_NOTES}
};

