/*
Notes to play the Iowa State Univerity's Fight Song

*/

Note isu_fight[] = {
  {NOTE_A3,  EIGHTH},
  {NOTE_A3,  SIXTEENTH},
  {NOTE_A3,  SIXTEENTH},
  {NOTE_A3,  EIGHTH},
  {NOTE_A3,  EIGHTH},
  
  {NOTE_A3,  EIGHTH},
  {NOTE_A3,  EIGHTH},
  {NOTE_B3,  EIGHTH},
  {NOTE_C4,  EIGHTH},

  {NOTE_D4,  QUARTER},
  {NOTE_F4,  EIGHTH},
  {NOTE_C4,  QUARTER},
  {NOTE_F4,  EIGHTH},

  {NOTE_B4,  QUARTER},
  {NOTE_D4,  EIGHTH},
  {NOTE_C4,  QUARTER},
  {NOTE_F4,  EIGHTH},
  
  {NOTE_F3,  EIGHTH},
  {NOTE_E3,  EIGHTH},
  {NOTE_F3,  QUARTER},
  {NOTE_A3,  EIGHTH},
  
  {NOTE_F3,  QUARTER},
  {NOTE_D4,  EIGHTH},
  {NOTE_C4,  EIGHTH},
  {NOTE_D4,  EIGHTH},
  
  {NOTE_E4,  QUARTER},
  {NOTE_A3,  EIGHTH},
  {NOTE_E4,  QUARTER},
  {NOTE_A3,  EIGHTH},
  
  {NOTE_C4,  QUARTER},
  {NOTE_E3,  EIGHTH},
  {NOTE_B4,  QUARTER},
  {NOTE_E3,  EIGHTH},
  
  {NOTE_G3,  DOTTEDHALF},
  
  {NOTE_B4,  EIGHTH},
  {NOTE_C4,  EIGHTH},
  {NOTE_D4,  EIGHTH},
  
  {NOTE_E4,  QUARTER},
  {NOTE_G4,  EIGHTH},
  {NOTE_D4,  QUARTER},
  {NOTE_G4,  EIGHTH},
  
  {NOTE_C4,  QUARTER},
  {NOTE_G4,  EIGHTH},
  {NOTE_B4,  QUARTER},
  {NOTE_E4,  EIGHTH},
  
  {NOTE_G3,  EIGHTH},
  {NOTE_F3,  EIGHTH},
  {NOTE_G3,  QUARTER},
  {NOTE_C4,  EIGHTH},
  
  {END_NOTES,  END_NOTES}  
  
};
